# Generated by Django 5.2.7 on 2025-11-04 06:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_lessons_completed', models.IntegerField(default=0)),
                ('total_problems_solved', models.IntegerField(default=0)),
                ('total_study_time_minutes', models.IntegerField(default=0)),
                ('total_exp_earned', models.IntegerField(default=0)),
                ('current_world', models.CharField(blank=True, max_length=50)),
                ('current_stage', models.IntegerField(default=1)),
                ('current_lesson', models.IntegerField(default=1)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('weekly_goal_days', models.IntegerField(default=5)),
                ('current_week_days', models.IntegerField(default=0)),
                ('week_start_date', models.DateField(blank=True, null=True)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('average_completion_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 진도',
                'db_table': 'user_progress',
            },
        ),
        migrations.CreateModel(
            name='DailyStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_date', models.DateField()),
                ('lessons_completed', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('exp_earned', models.IntegerField(default=0)),
                ('study_time_minutes', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('goal_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일일 학습 기록',
                'db_table': 'daily_studies',
                'ordering': ['-study_date'],
                'indexes': [models.Index(fields=['user', 'study_date'], name='daily_studi_user_id_83910a_idx'), models.Index(fields=['study_date'], name='daily_studi_study_d_f00783_idx')],
                'unique_together': {('user', 'study_date')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('world_name', models.CharField(max_length=50)),
                ('stage_number', models.IntegerField()),
                ('lesson_number', models.IntegerField()),
                ('status', models.CharField(choices=[('locked', '잠김'), ('unlocked', '해제됨'), ('in_progress', '진행 중'), ('completed', '완료됨'), ('mastered', '마스터')], default='locked', max_length=20)),
                ('total_problems', models.IntegerField(default=0)),
                ('solved_problems', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('total_time_seconds', models.IntegerField(default=0)),
                ('exp_earned', models.IntegerField(default=0)),
                ('first_started_at', models.DateTimeField(blank=True, null=True)),
                ('first_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '레슨 진도',
                'db_table': 'lesson_progress',
                'indexes': [models.Index(fields=['user', 'status'], name='lesson_prog_user_id_f63390_idx'), models.Index(fields=['world_name', 'stage_number'], name='lesson_prog_world_n_ca335f_idx')],
                'unique_together': {('user', 'world_name', 'stage_number', 'lesson_number')},
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('world_name', models.CharField(max_length=50)),
                ('stage_number', models.IntegerField()),
                ('lesson_number', models.IntegerField()),
                ('problems_attempted', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('exp_gained', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_successfully', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학습 세션',
                'db_table': 'study_sessions',
                'ordering': ['-session_start'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='study_sessi_user_id_1378c4_idx'), models.Index(fields=['session_start'], name='study_sessi_session_63f47b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorldProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('world_name', models.CharField(max_length=50)),
                ('total_stages', models.IntegerField(default=0)),
                ('completed_stages', models.IntegerField(default=0)),
                ('current_stage', models.IntegerField(default=1)),
                ('total_lessons', models.IntegerField(default=0)),
                ('completed_lessons', models.IntegerField(default=0)),
                ('exp_earned', models.IntegerField(default=0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '월드 진도',
                'db_table': 'world_progress',
                'unique_together': {('user', 'world_name')},
            },
        ),
    ]
