# Generated by Django 5.2.7 on 2025-11-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_socialaccount_user_deleted_at_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
    ]
