# Generated by Django 5.2.7 on 2025-11-05 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='예: Python, Java, Javascript', max_length=100, verbose_name='코딩 언어 월드')),
                ('description', models.TextField(verbose_name='월드 설명')),
                ('icon', models.CharField(help_text='이모지', max_length=50, verbose_name='아이콘')),
                ('is_locked', models.BooleanField(default=True, verbose_name='잠금 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '코딩 언어',
                'verbose_name_plural': '코딩 언어 목록',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='스테이지 제목')),
                ('description', models.TextField(blank=True, verbose_name='스테이지 설명')),
                ('order', models.IntegerField(verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='worlds.world', verbose_name='월드')),
            ],
            options={
                'verbose_name': '스테이지',
                'verbose_name_plural': '스테이지 목록',
                'ordering': ['order'],
                'unique_together': {('world', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료여부')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.stage', verbose_name='스테이지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '스테이지 진행 상황',
                'verbose_name_plural': '스테이지 진행상황 목록',
                'unique_together': {('user', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='UserWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False, verbose_name='잠금 해제 여부')),
                ('completed_stage', models.IntegerField(default=0, verbose_name='완료한 스테이지 수')),
                ('last_studied_at', models.DateTimeField(blank=True, help_text='레슨을 풀었을때만 업데이트', null=True, verbose_name='마지막 공부 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_worlds', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='worlds.world', verbose_name='월드')),
            ],
            options={
                'verbose_name': '사용자 코딩 언어 월드',
                'verbose_name_plural': '사용자 월드 진행 사항 목록',
                'ordering': ['-last_studied_at', '-created_at'],
                'unique_together': {('user', 'world')},
            },
        ),
    ]
