# Generated by Django 5.2.7 on 2025-11-04 13:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_socialaccount_user_deleted_at_user_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TierConfig',
            fields=[
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master'), ('LEGEND', 'Legend')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('min_exp', models.IntegerField(verbose_name='최소 EXP')),
                ('max_exp', models.IntegerField(verbose_name='최대 EXP')),
                ('icon', models.CharField(max_length=10, verbose_name='아이콘')),
                ('color', models.CharField(max_length=7, verbose_name='색상 코드')),
                ('order', models.IntegerField(unique=True, verbose_name='순서')),
                ('coin_multiplier', models.FloatField(default=1.0, verbose_name='코인 배율')),
            ],
            options={
                'verbose_name': '티어 설정',
                'verbose_name_plural': '티어 설정 목록',
                'db_table': 'tier_configs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GlobalRanking',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='global_ranking', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rank', models.IntegerField(db_index=True, verbose_name='전체 순위')),
                ('total_exp', models.IntegerField(default=0, verbose_name='총 EXP')),
                ('current_tier', models.CharField(db_index=True, max_length=20, verbose_name='현재 티어')),
                ('total_coding_problems', models.IntegerField(default=0, verbose_name='총 코딩 문제 수')),
                ('total_cert_problems', models.IntegerField(default=0, verbose_name='총 자격증 문제 수')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='마지막 업데이트')),
            ],
            options={
                'verbose_name': '전체 랭킹',
                'verbose_name_plural': '전체 랭킹 목록',
                'db_table': 'global_rankings',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['rank'], name='global_rank_rank_7c0bb8_idx'), models.Index(fields=['current_tier', 'rank'], name='global_rank_current_84c70c_idx')],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master'), ('LEGEND', 'Legend')], db_index=True, max_length=20)),
                ('week_start', models.DateField(db_index=True, verbose_name='리그 시작일')),
                ('week_end', models.DateField(verbose_name='리그 종료일')),
                ('max_participants', models.IntegerField(default=50, verbose_name='최대 참가자 수')),
                ('current_participants', models.IntegerField(default=0, verbose_name='현재 참가자 수')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='활성 상태')),
                ('is_finished', models.BooleanField(default=False, verbose_name='종료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '리그',
                'verbose_name_plural': '리그 목록',
                'db_table': 'leagues',
                'ordering': ['-week_start', 'tier'],
                'indexes': [models.Index(fields=['tier', 'week_start', 'is_active'], name='leagues_tier_bdabe9_idx'), models.Index(fields=['is_active', 'is_finished'], name='leagues_is_acti_b71f70_idx')],
                'unique_together': {('tier', 'week_start', 'league_id')},
            },
        ),
        migrations.CreateModel(
            name='LeagueParticipant',
            fields=[
                ('participant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekly_coding_exp', models.IntegerField(default=0, verbose_name='주간 코딩 EXP')),
                ('weekly_cert_exp', models.IntegerField(default=0, verbose_name='주간 자격증 EXP')),
                ('current_rank', models.IntegerField(db_index=True, default=0, verbose_name='현재 순위')),
                ('previous_rank', models.IntegerField(default=0, verbose_name='이전 순위')),
                ('highest_rank', models.IntegerField(default=0, verbose_name='최고 순위')),
                ('status', models.CharField(choices=[('SAFE', 'Safe'), ('PROMOTION', 'Promotion'), ('DEMOTION', 'Demotion')], default='SAFE', max_length=20, verbose_name='승급/강등 상태')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 활동 시간')),
                ('total_activities', models.IntegerField(default=0, verbose_name='총 활동 횟수')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='참가 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rank.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '리그 참가자',
                'verbose_name_plural': '리그 참가자 목록',
                'db_table': 'league_participants',
                'ordering': ['current_rank', 'joined_at'],
                'indexes': [models.Index(fields=['league', 'current_rank'], name='league_part_league__3e6f29_idx'), models.Index(fields=['user', 'league'], name='league_part_user_id_150912_idx'), models.Index(fields=['-weekly_coding_exp', '-weekly_cert_exp'], name='league_part_weekly__7ea376_idx')],
                'unique_together': {('league', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserRankingHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_rank', models.IntegerField(verbose_name='최종 순위')),
                ('final_exp', models.IntegerField(verbose_name='최종 EXP')),
                ('final_coding_exp', models.IntegerField(verbose_name='최종 코딩 EXP')),
                ('final_cert_exp', models.IntegerField(verbose_name='최종 자격증 EXP')),
                ('result', models.CharField(choices=[('PROMOTED', 'Promoted'), ('DEMOTED', 'Demoted'), ('MAINTAINED', 'Maintained')], max_length=20, verbose_name='결과')),
                ('reward_coins', models.IntegerField(default=0, verbose_name='획득 코인')),
                ('reward_items', models.JSONField(blank=True, default=dict, verbose_name='획득 아이템')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 시간')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='rank.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '랭킹 히스토리',
                'verbose_name_plural': '랭킹 히스토리 목록',
                'db_table': 'user_ranking_history',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', '-recorded_at'], name='user_rankin_user_id_9db702_idx'), models.Index(fields=['league', 'final_rank'], name='user_rankin_league__da6f2c_idx')],
            },
        ),
    ]
